[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
bank = "46ZGHfPxd5JbtCbAnYUKXcHuoqkQQHDWQTcphxA5aeQM"
dlp = "G7uEs9veqxboMC7kCwpnduLq57GnhKD2T1t3SqbgafQR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
